/*
 * EE 4065 - Embedded Digital Image Processing
 * Placeholder for YOLO Digit Detection Model
 * 
 * Student: KAAN ATALAY
 * ID: 150720057
 * 
 * This file will contain the trained model as a C array.
 * After training, convert using: xxd -i model.tflite > digit_model.h
 */

#ifndef DIGIT_MODEL_H
#define DIGIT_MODEL_H

// Placeholder - Replace with actual model after training
// The actual model will be generated by running train_yolo_digit.py
// and converting the output TFLite model to C array

// Model size placeholder (actual size will vary based on training)
#define DIGIT_MODEL_SIZE 150000

// Model data array - to be filled after training
alignas(16) const unsigned char digit_model_tflite[] = {
    // Model bytes will go here after conversion
    // Example command: xxd -i digit_detection_int8.tflite > digit_model.h
    0x00  // Placeholder byte
};

const unsigned int digit_model_tflite_len = sizeof(digit_model_tflite);

/*
 * INSTRUCTIONS TO GENERATE THIS FILE:
 * 
 * 1. Run train_yolo_digit.py on PC to train the model
 * 2. The script will export digit_detection_int8.tflite
 * 3. Convert to C array:
 *    xxd -i digit_detection_int8.tflite > digit_model.h
 * 4. Replace this placeholder with the generated content
 * 5. Ensure the array is aligned: alignas(16) const unsigned char...
 */

#endif // DIGIT_MODEL_H
